spring.application.name=CATALOG-SERVICE
spring.profiles.active=dev

# Eureka
# 1. Prefer IP over Hostname
eureka.instance.prefer-ip-address=true

# 2. Use your local IP (127.0.0.1) for internal routing
eureka.instance.ip-address=127.0.0.1

# 3. (Optional) Force the instance ID to show the IP in the dashboard
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

# 4. Shorten the lease so Eureka updates faster
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# JPA
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration